### ISSUE TITLE
Test coverage on PR

### ISSUE THREAD

**Issue by masch** [golang-templates/seed#41]
Hi!

Have you ever considered to add a Github action on PR to messure the test coverage of it?

I love your golang template project!
Thanks!

**Comment by pellared** [comment]
@masch 
First of all, thanks a lot for both the question and feedback.

Could you please try to specify how it should behave to avoid misunderstanding. 
Alternatively (or even additionally) you can also send some example project where it is done.

PS. Some time ago I was thinking of creating to add a coverage badge, but I found that it would probably require to add a dependency + manual configuration with a service like https://coveralls.io/ or https://codecov.io/ which I am not sure if it is a good idea. Moreover, the "default" test coverage shows only coverage for the package being tested (it does not show coverage of dependant packages. For some devs it is OK for others it is not. It depends on the test strategy and application/library design as well. More info: https://www.ory.sh/golang-go-code-coverage-accurate/ .

**Comment by masch** [comment]
You are totally right, measuring test coverage is a little tricky on Golang. As a internal convention, we do unit test on every package and measure them package by package. Also we are integration/functional test in order to increase the changes to catch a e2e bug. After the tests run fine, we have an internal tool that takes the output from the `go test` and then convert it to some internal coverage report. Too much fixed for the company that I work.
In the past, I used to configure my personal projects with Codedov but also it has the down side of multiple configuration by project.
So I was asking my self, What is a good and generic solution to use on this templates project?
I don't have a good answer, I was asking to know what is your opinion on this kind of tool and how could I help in order to work on it?

**Comment by pellared** [comment]
# Analysis

I think that there are two problematic things that can be distinguished here.

## Executing go test with test coverage

I think that we can update the `test` target to something like:
```
go test -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./...
```
And add `coverage.txt` to `.gitignore`.
Alternatively we can put `coverage.txt` under some directory like `tmp`.
What do you think?

## Where to output the test coverage result

Right now I see the following options:

### HTML artifact

Create HTML output created using `go tool cover -html=coverage.txt` and as build artifact so that it can be downloaded and analyzed locally. Reference: https://blog.golang.org/cover

Benefits:
1. Can be used even locally (new make target) to analyze coverage during development
1. No initialization steps required after "using" the template

Drawbacks:
1. https://github.com/actions/upload-artifact always zips the artifacts. Lots of steps if someone wants to check the coverage when e.g. reviewing a PR ❓ _TO BE VERFIED_
1. Lacks historical analysis, comparisons, graphs, PR reports etc.

### [Codecov](https://codecov.io/)

An example project using Codecov: https://github.com/goreleaser/goreleaser.
Example PR report thanks to [codecov-action](https://github.com/codecov/codecov-action): https://github.com/goreleaser/goreleaser/pull/1503#issuecomment-626399925. 

Benefits:
1. Historical analysis, comparisons, graphs etc
1. PR reports
1. Free not only for public repos but also private repos with up to 5 users

Drawbacks:
1. Requires setup after "using" the template
1. Not suited for local development ❓ _TO BE VERFIED_

### [Coveralls](https://coveralls.io/)

An example project using Coveralls: https://github.com/mattn/goveralls.
Example PR report thanks: https://github.com/mattn/goveralls/pull/169#issuecomment-633327979. ❓ I have no idea how it was configured 

Similar benefits and drawbacks to Codecov.

# Next steps

What I propose for now is that I can try making a PR with better code coverage and HTML coverage output in artifacts. 

In the meantime, you could compare Codecov and Coveralls in practice on some forks.

I think that there is nothing against having both the coverage in HTML file and Codecov or Coveralls at the same time. My first impression (but without configuring it myself) is that Codecov seems to be slightly better and also has a better pricing plan. Also, I feel that the setup should be easy and most of the steps are still needed to be done manually. I think we can end up with a FAQ section how to setup Codecov for a new project created using this template.

Please feel free to comment, agree and disagree. Your feedback, help and experience is more than welcome.

**Comment by masch** [comment]
I think it a greet start from you deeply research, nice work. Here are my comments:

> Executing go test with test coverage

Yeah, it a great use `go tool cover` with the html result for local environment, I use it a lot before I commit a PR. 
I think the parameters options are quite enough to get a grate report and especially the `-race` flag, It catches a lot of tricky :beetle:.  

Also as I'm a big fun of the use of terminal, I also use [goverreport](https://github.com/mcubik/goverreport) tool to get an easy test measure. Do you know it?
I would love to have that kind of report with a Github action on PR's comments.


 > HTML artifact

I didn't know it, so from what I red it could be a good output of test result, but personally I prefer a PR's comment like Codecov does it. But if a user doesn't want to use an external tool, it will be very useful.


> Codecov vs Coveralls

Both tools and test coverage mechanism are great. I know Coverall but I never use it on my projects, but I use a lot Codecov. So in my personal experience, I would prefer the use of Codecov. The heat map on PR's comments and the UI on their web are better than Coveralls.
As you mentioned, I think the use of this tools should be optional on the project template with a FAQ how to setup it on a new project.


> Next steps
I think it's a great start the one that you have proposed it, If you want to I could do a POC with it.

**Comment by pellared** [comment]
Can you please review:  https://github.com/golang-templates/seed/pull/43 

Doing a PoC with Codecov would help me :wink: 

Thanks for sharing goverreport with me. However, I do not know how I could integrate it right now.

Currently I think of following improvements for this repo:
1. Integration with Codecov (at least FAQ section how to do it if it would not make sense to automate it - maybe provide some example repository where it is configured as reference)
1. Integraton with [Dependabot](https://dependabot.com/go/). Now it is nicley [integrated with GitHub](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/).
1. Experiment with [reviewdog](https://github.com/reviewdog/reviewdog). I think it can be used to add comments to PRs on build, lint and test errors.
1. I want to make something to help with dependency licensing (validation and reporting), but have not found any good free solution that would support Go Modules.

**Comment by masch** [comment]
Great! All the improvements are wonderful I can't wait to see on the road! :tada:

**Comment by pellared** [comment]
@masch 
I had some time today to play with Codecov. Could you please test and review this PR: https://github.com/golang-templates/seed/pull/47 ?

**Comment by masch** [comment]
Hey! @pellared 
I'm sorry for the delay, I've used your PR and I've integrated Codecov with GH actions on my project.
Great momentum with a lot of feature!

**Comment by masch** [comment]
Thank you for the invitation!! :tada:

**Comment by pellared** [comment]
@masch I am happy that I could help you. 

Please feel free to create a new issue if you have some idea how to improve this repository template.
