### ISSUE TITLE
Change to Mage so we can have CI run on other OSes

### ISSUE THREAD

**Issue by joe-getcouragenow** [golang-templates/seed#68]
makefiles are awesome, but a simple mage file can allow us to run on all Os's in Github CI.

**Comment by pellared** [comment]
Hi @joe-getcouragenow ,

First of all, thanks for the feedback.

Initially this template was using [Mage](https://github.com/magefile/mage). See: https://github.com/golang-templates/seed/tree/v0.1.1
It has been removed mainly, because I got a lot of feedback from the community that they prefer [Make](https://www.gnu.org/software/make/) and this is the most popular tool used to automate builds in Go.

Personally I have been experimenting a bit with Mage and while I like that it is Go I dislike the design that it is more like a framework (I would prefer to have a library), it is hard to debug (even the author admitted that he was never doing it) and its parallel dependencies are not really helpful as Mage does not provide any way to synchronize targets' output that is run in parallel. I find Mage to magical (even as the name suggests :smile: ). That are only a few stuff that I dislike after playing a few weeks with Mage.

I plan to experiment with creating a PoC library for making build pipelines in Go as CLI apps that would address stuff that I dislike in Mage. Maybe I will even create it in following days. I will let you know when I have something so you can give me some feedback. Still I would probably not use this library in this template as I favor community standards over my own preferences.

**Comment by pellared** [comment]
@joe-getcouragenow Can you review  https://github.com/pellared/taskflow and tell if you think I should use it here?

**Comment by pellared** [comment]
@joe-getcouragenow There was no issue running anything on other OSes. See: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
Closing
